
 # select f.internal_id  -- , ap.`tag`, ap.`is_accredited`, an.delivery_report_created_at
 # from family as f
 # join family_sample as f_s on f_s.family_id = f.id
 # join sample as s on s.id = f_s.sample_id
 # join `application_version` as a_v on a_v.id = s.application_version_id
 # join application as ap on ap.id = a_v.`application_id`
 # join analysis as an on an.family_id = f.id
 # where an.delivery_report_created_at > "2020-04-14" and an.delivery_report_created_at < "2020-11-20" and f.data_analysis = 'mip-dna' and an.`delivery_report_created_at` IS not NULL and ap.`is_accredited` = 0
 # group by f.internal_id
 # order by an.`delivery_report_created_at` ;

usestage;

cg upload delivery-report -f ablebull
cg upload delivery-report -f ablehusky
cg upload delivery-report -f abovedingo
cg upload delivery-report -f aboveroughy
cg upload delivery-report -f abovetick
cg upload delivery-report -f acemarten
cg upload delivery-report -f acetroll
cg upload delivery-report -f activebuck
cg upload delivery-report -f activefly
cg upload delivery-report -f activefowl
cg upload delivery-report -f activetoad
cg upload delivery-report -f actualcondor
cg upload delivery-report -f actualeel
cg upload delivery-report -f actualhound
cg upload delivery-report -f actualjoey
cg upload delivery-report -f actualtomcat
cg upload delivery-report -f alertinsect
cg upload delivery-report -f alertweasel
cg upload delivery-report -f alivecondor
cg upload delivery-report -f alivegoat
cg upload delivery-report -f aliveweasel
cg upload delivery-report -f amazedape
cg upload delivery-report -f amazedorca
cg upload delivery-report -f amazedracer
cg upload delivery-report -f amazedrobin
cg upload delivery-report -f amazedshrimp
cg upload delivery-report -f ampleheron
cg upload delivery-report -f ampleoryx
cg upload delivery-report -f amusedcalf
cg upload delivery-report -f amusedgar
cg upload delivery-report -f aptbug
cg upload delivery-report -f aptcougar
cg upload delivery-report -f apttahr
cg upload delivery-report -f awaremantis
cg upload delivery-report -f betterlark
cg upload delivery-report -f bettermutt
cg upload delivery-report -f bettertick
cg upload delivery-report -f bigcicada
cg upload delivery-report -f bigdonkey
cg upload delivery-report -f bigibex
cg upload delivery-report -f bigtoad
cg upload delivery-report -f boldalien
cg upload delivery-report -f boldkoala
cg upload delivery-report -f boldtick
cg upload delivery-report -f bossbedbug
cg upload delivery-report -f bosspug
cg upload delivery-report -f bravedassie
cg upload delivery-report -f bravefilly
cg upload delivery-report -f bravesnipe
cg upload delivery-report -f briefsheep
cg upload delivery-report -f briefvervet
cg upload delivery-report -f briefweasel
cg upload delivery-report -f brightbat
cg upload delivery-report -f brightdrake
cg upload delivery-report -f brighthyena
cg upload delivery-report -f brightlamb
cg upload delivery-report -f brightshiner
cg upload delivery-report -f busyboxer
cg upload delivery-report -f busyimp
cg upload delivery-report -f busykid
cg upload delivery-report -f calmfowl
cg upload delivery-report -f calmgoose
cg upload delivery-report -f calmmarmot
cg upload delivery-report -f calmpup
cg upload delivery-report -f caringbuck
cg upload delivery-report -f caringgnat
cg upload delivery-report -f caringmagpie
cg upload delivery-report -f casualeft
cg upload delivery-report -f casualpony
cg upload delivery-report -f casualskink
cg upload delivery-report -f causalcivet
cg upload delivery-report -f causalprawn
cg upload delivery-report -f causalswift
cg upload delivery-report -f chiefdonkey
cg upload delivery-report -f chiefgrub
cg upload delivery-report -f civilcollie
cg upload delivery-report -f civilgull
cg upload delivery-report -f civillark
cg upload delivery-report -f cleanworm
cg upload delivery-report -f cleanzebra
cg upload delivery-report -f clearape
cg upload delivery-report -f clearcow
cg upload delivery-report -f clearlab
cg upload delivery-report -f clearmouse
cg upload delivery-report -f cleverhound
cg upload delivery-report -f cleverlizard
cg upload delivery-report -f cleveryeti
cg upload delivery-report -f closefish
cg upload delivery-report -f closegator
cg upload delivery-report -f closeoyster
cg upload delivery-report -f closeturkey
cg upload delivery-report -f comicbird
cg upload delivery-report -f comicbuck
cg upload delivery-report -f comicfeline
cg upload delivery-report -f comicpuma
cg upload delivery-report -f comicwasp
cg upload delivery-report -f coolcrane
cg upload delivery-report -f coolhawk
cg upload delivery-report -f coolpig
cg upload delivery-report -f coolrabbit
cg upload delivery-report -f coolshad
cg upload delivery-report -f crackmartin
cg upload delivery-report -f crispowl
cg upload delivery-report -f cuddlybaboon
cg upload delivery-report -f cuddlystud
cg upload delivery-report -f cutetrout
cg upload delivery-report -f daringcattle
cg upload delivery-report -f daringfish
cg upload delivery-report -f daringpuma
cg upload delivery-report -f dearhare
cg upload delivery-report -f dearpigeon
cg upload delivery-report -f decentibex
cg upload delivery-report -f decentpuma
cg upload delivery-report -f deepmaggot
cg upload delivery-report -f deepmidge
cg upload delivery-report -f divinepuma
cg upload delivery-report -f drivenbream
cg upload delivery-report -f eagertapir
cg upload delivery-report -f easygannet
cg upload delivery-report -f easygoblin
cg upload delivery-report -f easylocust
cg upload delivery-report -f easylouse
cg upload delivery-report -f enoughcrane
cg upload delivery-report -f epicdassie
cg upload delivery-report -f equalchow
cg upload delivery-report -f equalturkey
cg upload delivery-report -f exactdodo
cg upload delivery-report -f exactstork
cg upload delivery-report -f exactwhale
cg upload delivery-report -f exoticdragon
cg upload delivery-report -f exotickid
cg upload delivery-report -f exoticmarmot
cg upload delivery-report -f expertmonkey
cg upload delivery-report -f fairfly
cg upload delivery-report -f fairgecko
cg upload delivery-report -f fairtarpon
cg upload delivery-report -f fancywalrus
cg upload delivery-report -f fastbug
cg upload delivery-report -f fastspider
cg upload delivery-report -f fasttoucan
cg upload delivery-report -f fineant
cg upload delivery-report -f fineglider
cg upload delivery-report -f finegull
cg upload delivery-report -f finerant
cg upload delivery-report -f finerimp
cg upload delivery-report -f finermouse
cg upload delivery-report -f finervervet
cg upload delivery-report -f finesole
cg upload delivery-report -f fineturtle
cg upload delivery-report -f firmbengal
cg upload delivery-report -f firmlouse
cg upload delivery-report -f firstimp
cg upload delivery-report -f fitgnu
cg upload delivery-report -f fitheron
cg upload delivery-report -f fitsole
cg upload delivery-report -f fittrout
cg upload delivery-report -f fleetbug
cg upload delivery-report -f fleetdeer
cg upload delivery-report -f fleethound
cg upload delivery-report -f fluentalien
cg upload delivery-report -f flyingmayfly
cg upload delivery-report -f fondcrow
cg upload delivery-report -f fondkitten
cg upload delivery-report -f fondman
cg upload delivery-report -f fondseal
cg upload delivery-report -f franksloth
cg upload delivery-report -f freequail
cg upload delivery-report -f freshskink
cg upload delivery-report -f fullkite
cg upload delivery-report -f fulllynx
cg upload delivery-report -f fullmantis
cg upload delivery-report -f fullperch
cg upload delivery-report -f funcow
cg upload delivery-report -f funnycamel
cg upload delivery-report -f funnyfish
cg upload delivery-report -f funnymite
cg upload delivery-report -f funswine
cg upload delivery-report -f funwasp
cg upload delivery-report -f gamecod
cg upload delivery-report -f gamehawk
cg upload delivery-report -f gamekiwi
cg upload delivery-report -f gamestag
cg upload delivery-report -f gamewhale
cg upload delivery-report -f gentlecougar
cg upload delivery-report -f gentlewhale
cg upload delivery-report -f givingbee
cg upload delivery-report -f givingcattle
cg upload delivery-report -f givingtoad
cg upload delivery-report -f givingweasel
cg upload delivery-report -f gladpoodle
cg upload delivery-report -f gladrodent
cg upload delivery-report -f goldenalpaca
cg upload delivery-report -f goldenpoodle
cg upload delivery-report -f goodbug
cg upload delivery-report -f grownbadger
cg upload delivery-report -f grownewe
cg upload delivery-report -f grownfilly
cg upload delivery-report -f growngnu
cg upload delivery-report -f grownhippo
cg upload delivery-report -f guidedlark
cg upload delivery-report -f handymoose
cg upload delivery-report -f handysheep
cg upload delivery-report -f handythrush
cg upload delivery-report -f happymaggot
cg upload delivery-report -f hardyfeline
cg upload delivery-report -f hardygnat
cg upload delivery-report -f hardyspider
cg upload delivery-report -f hardytahr
cg upload delivery-report -f heroicloon
cg upload delivery-report -f heroicwalrus
cg upload delivery-report -f hipdog
cg upload delivery-report -f hipdrum
cg upload delivery-report -f holytetra
cg upload delivery-report -f honestalien
cg upload delivery-report -f honestcamel
cg upload delivery-report -f honestcod
cg upload delivery-report -f honestfilly
cg upload delivery-report -f honestmoth
cg upload delivery-report -f honesttiger
cg upload delivery-report -f hotguppy
cg upload delivery-report -f hotllama
cg upload delivery-report -f hotmacaw
cg upload delivery-report -f hotswine
cg upload delivery-report -f hugeelf
cg upload delivery-report -f hugefilly
cg upload delivery-report -f hugemoray
cg upload delivery-report -f humaneasp
cg upload delivery-report -f humaneosprey
cg upload delivery-report -f humanetahr
cg upload delivery-report -f humblecrab
cg upload delivery-report -f humbledoe
cg upload delivery-report -f humblepiglet
cg upload delivery-report -f humblestag
cg upload delivery-report -f humbleviper
cg upload delivery-report -f humblewalrus
cg upload delivery-report -f idealbat
cg upload delivery-report -f idealkit
cg upload delivery-report -f idealkitten
cg upload delivery-report -f idealsquid
cg upload delivery-report -f immunetoucan
cg upload delivery-report -f incalf
cg upload delivery-report -f incolt
cg upload delivery-report -f inpig
cg upload delivery-report -f jointcobra
cg upload delivery-report -f jointdeer
cg upload delivery-report -f justcrow
cg upload delivery-report -f justhog
cg upload delivery-report -f justpup
cg upload delivery-report -f justyak
cg upload delivery-report -f keenelf
cg upload delivery-report -f keensheep
cg upload delivery-report -f keyhen
cg upload delivery-report -f keyquail
cg upload delivery-report -f kindvervet
cg upload delivery-report -f knownboxer
cg upload delivery-report -f knowncrane
cg upload delivery-report -f largelouse
cg upload delivery-report -f legalloon
cg upload delivery-report -f legalsole
cg upload delivery-report -f legalwombat
cg upload delivery-report -f lightmacaw
cg upload delivery-report -f lightpoodle
cg upload delivery-report -f lighttomcat
cg upload delivery-report -f likedghoul
cg upload delivery-report -f liveflea
cg upload delivery-report -f livewhale
cg upload delivery-report -f livingchimp
cg upload delivery-report -f lovingslug
cg upload delivery-report -f loyalclam
cg upload delivery-report -f loyalsole
cg upload delivery-report -f loyaltoucan
cg upload delivery-report -f loyalwasp
cg upload delivery-report -f luckypossum
cg upload delivery-report -f mainbeagle
cg upload delivery-report -f maingecko
cg upload delivery-report -f mainhog
cg upload delivery-report -f mainpoodle
cg upload delivery-report -f mainyeti
cg upload delivery-report -f majorasp
cg upload delivery-report -f majorcorgi
cg upload delivery-report -f majorfrog
cg upload delivery-report -f majorstag
cg upload delivery-report -f manycrow
cg upload delivery-report -f manyelk
cg upload delivery-report -f manygibbon
cg upload delivery-report -f matureeft
cg upload delivery-report -f meetbull
cg upload delivery-report -f meetguinea
cg upload delivery-report -f meethawk
cg upload delivery-report -f merrycaiman
cg upload delivery-report -f merryferret
cg upload delivery-report -f merryyak
cg upload delivery-report -f mightycow
cg upload delivery-report -f mightykoi
cg upload delivery-report -f mightymarlin
cg upload delivery-report -f mightyweevil
cg upload delivery-report -f mintdassie
cg upload delivery-report -f mintgrouse
cg upload delivery-report -f modelfowl
cg upload delivery-report -f modelmole
cg upload delivery-report -f modelsnipe
cg upload delivery-report -f modernliger
cg upload delivery-report -f modestbeetle
cg upload delivery-report -f modestghoul
cg upload delivery-report -f modestmidge
cg upload delivery-report -f modestpug
cg upload delivery-report -f modestshiner
cg upload delivery-report -f modestwombat
cg upload delivery-report -f moralduck
cg upload delivery-report -f moralhen
cg upload delivery-report -f moralleech
cg upload delivery-report -f morallocust
cg upload delivery-report -f moralloon
cg upload delivery-report -f moralmoth
cg upload delivery-report -f movinghare
cg upload delivery-report -f movingram
cg upload delivery-report -f mutualcougar
cg upload delivery-report -f nativegopher
cg upload delivery-report -f nativelark
cg upload delivery-report -f nativemuskox
cg upload delivery-report -f nearbyakita
cg upload delivery-report -f nearbyeagle
cg upload delivery-report -f nearbygull
cg upload delivery-report -f nearbyllama
cg upload delivery-report -f neatturtle
cg upload delivery-report -f neededfly
cg upload delivery-report -f nextgannet
cg upload delivery-report -f nextseal
cg upload delivery-report -f nicewren
cg upload delivery-report -f nobleeagle
cg upload delivery-report -f nobleegret
cg upload delivery-report -f noblegoat
cg upload delivery-report -f noblehen
cg upload delivery-report -f noblerodent
cg upload delivery-report -f nobleshad
cg upload delivery-report -f nobleswift
cg upload delivery-report -f notedrat
cg upload delivery-report -f notedsalmon
cg upload delivery-report -f novelsnail
cg upload delivery-report -f onasp
cg upload delivery-report -f onboa
cg upload delivery-report -f oneheron
cg upload delivery-report -f onglider
cg upload delivery-report -f opendeer
cg upload delivery-report -f opendory
cg upload delivery-report -f openhen
cg upload delivery-report -f pickeddoe
cg upload delivery-report -f pickedgrub
cg upload delivery-report -f pickedgull
cg upload delivery-report -f pickedkiwi
cg upload delivery-report -f pickedram
cg upload delivery-report -f pickedswine
cg upload delivery-report -f politeboxer
cg upload delivery-report -f politesawfly
cg upload delivery-report -f prettymole
cg upload delivery-report -f primechow
cg upload delivery-report -f primecoyote
cg upload delivery-report -f primeeft
cg upload delivery-report -f primehorse
cg upload delivery-report -f primelion
cg upload delivery-report -f primeparrot
cg upload delivery-report -f primerobin
cg upload delivery-report -f primethrush
cg upload delivery-report -f primeweasel
cg upload delivery-report -f promole
cg upload delivery-report -f promptgull
cg upload delivery-report -f promptman
cg upload delivery-report -f promptram
cg upload delivery-report -f promptswine
cg upload delivery-report -f properrhino
cg upload delivery-report -f prouddrake
cg upload delivery-report -f provendodo
cg upload delivery-report -f provengopher
cg upload delivery-report -f provenmidge
cg upload delivery-report -f provenox
cg upload delivery-report -f pureboa
cg upload delivery-report -f purethrush
cg upload delivery-report -f quickwalrus
cg upload delivery-report -f quietparrot
cg upload delivery-report -f rapidcoyote
cg upload delivery-report -f rapidlab
cg upload delivery-report -f rapidmarlin
cg upload delivery-report -f readykoi
cg upload delivery-report -f realpython
cg upload delivery-report -f restedbeagle
cg upload delivery-report -f richmarlin
cg upload delivery-report -f rightfish
cg upload delivery-report -f rightrhino
cg upload delivery-report -f rightshiner
cg upload delivery-report -f rightyeti
cg upload delivery-report -f robustpanda
cg upload delivery-report -f rulingfilly
cg upload delivery-report -f rulingsheep
cg upload delivery-report -f rulingtarpon
cg upload delivery-report -f rulingweasel
cg upload delivery-report -f safecrane
cg upload delivery-report -f safelizard
cg upload delivery-report -f savedeel
cg upload delivery-report -f savedhare
cg upload delivery-report -f savedsnail
cg upload delivery-report -f savingbeagle
cg upload delivery-report -f savingkoi
cg upload delivery-report -f securefish
cg upload delivery-report -f secureimp
cg upload delivery-report -f securekit
cg upload delivery-report -f securekrill
cg upload delivery-report -f selectmarlin
cg upload delivery-report -f selectoriole
cg upload delivery-report -f selectturkey
cg upload delivery-report -f setmonkey
cg upload delivery-report -f setoriole
cg upload delivery-report -f setsponge
cg upload delivery-report -f simplebengal
cg upload delivery-report -f simpledove
cg upload delivery-report -f simplelocust
cg upload delivery-report -f simplerodent
cg upload delivery-report -f simpleroughy
cg upload delivery-report -f smartraven
cg upload delivery-report -f smartsquid
cg upload delivery-report -f smoothaphid
cg upload delivery-report -f smoothgoblin
cg upload delivery-report -f smoothpoodle
cg upload delivery-report -f smoothtarpon
cg upload delivery-report -f soliddory
cg upload delivery-report -f solidorca
cg upload delivery-report -f solidpika
cg upload delivery-report -f solidwombat
cg upload delivery-report -f soughtbeetle
cg upload delivery-report -f soughtgnat
cg upload delivery-report -f soughtimpala
cg upload delivery-report -f soughtkit
cg upload delivery-report -f soughtkoi
cg upload delivery-report -f soundcattle
cg upload delivery-report -f soundegret
cg upload delivery-report -f soundhare
cg upload delivery-report -f soundwasp
cg upload delivery-report -f squarebird
cg upload delivery-report -f squarecolt
cg upload delivery-report -f squarecoyote
cg upload delivery-report -f squarekoala
cg upload delivery-report -f stablemidge
cg upload delivery-report -f stargnat
cg upload delivery-report -f stariguana
cg upload delivery-report -f starsnail
cg upload delivery-report -f steadygull
cg upload delivery-report -f steadysole
cg upload delivery-report -f strongboxer
cg upload delivery-report -f stronghound
cg upload delivery-report -f suitedhornet
cg upload delivery-report -f suitedimp
cg upload delivery-report -f suitedmolly
cg upload delivery-report -f suitedmuskox
cg upload delivery-report -f suitedsquid
cg upload delivery-report -f superbstud
cg upload delivery-report -f superburro
cg upload delivery-report -f superdingo
cg upload delivery-report -f superskunk
cg upload delivery-report -f superwren
cg upload delivery-report -f sureleech
cg upload delivery-report -f sureswine
cg upload delivery-report -f surewalrus
cg upload delivery-report -f sweetmartin
cg upload delivery-report -f tightflea
cg upload delivery-report -f topfish
cg upload delivery-report -f topsbengal
cg upload delivery-report -f topsdragon
cg upload delivery-report -f topsgoose
cg upload delivery-report -f toughbug
cg upload delivery-report -f toughfowl
cg upload delivery-report -f toughkit
cg upload delivery-report -f toughlocust
cg upload delivery-report -f toughsponge
cg upload delivery-report -f toughwalrus
cg upload delivery-report -f trueburro
cg upload delivery-report -f truecollie
cg upload delivery-report -f truestud
cg upload delivery-report -f trustysloth
cg upload delivery-report -f uniquegoat
cg upload delivery-report -f unitedgrouse
cg upload delivery-report -f unitedllama
cg upload delivery-report -f upowl
cg upload delivery-report -f upwardcow
cg upload delivery-report -f upwardfox
cg upload delivery-report -f upwardkiwi
cg upload delivery-report -f upwardminnow
cg upload delivery-report -f usefulbee
cg upload delivery-report -f usefuleft
cg upload delivery-report -f usefulhen
cg upload delivery-report -f usefuljennet
cg upload delivery-report -f validbird
cg upload delivery-report -f validfrog
cg upload delivery-report -f validglider
cg upload delivery-report -f validpika
cg upload delivery-report -f validpup
cg upload delivery-report -f validraptor
cg upload delivery-report -f valuedbass
cg upload delivery-report -f valuedbunny
cg upload delivery-report -f valuedraptor
cg upload delivery-report -f vastgibbon
cg upload delivery-report -f vasthippo
cg upload delivery-report -f vastrabbit
cg upload delivery-report -f viablewhale
cg upload delivery-report -f vitalbengal
cg upload delivery-report -f vitalkiwi
cg upload delivery-report -f vitalloon
cg upload delivery-report -f vitalmonkey
cg upload delivery-report -f vitalpika
cg upload delivery-report -f vocalboar
cg upload delivery-report -f vocalsquid
cg upload delivery-report -f wantedshad
cg upload delivery-report -f warmcicada
cg upload delivery-report -f warmmink
cg upload delivery-report -f warmserval
cg upload delivery-report -f wellflea
cg upload delivery-report -f wholekite
cg upload delivery-report -f wiredkoi
cg upload delivery-report -f wiredpup
cg upload delivery-report -f wiredtapir
cg upload delivery-report -f wiredtomcat
cg upload delivery-report -f wisecamel
cg upload delivery-report -f wisecat
cg upload delivery-report -f wisejennet
cg upload delivery-report -f wittycollie
cg upload delivery-report -f wittyraptor
cg upload delivery-report -f worthychow
cg upload delivery-report -f worthyinsect
cg upload delivery-report -f worthyraptor
cg upload delivery-report -f worthyswift
